seed = 5
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 7
num_embedding_arch = [
    "autodis",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
positional_encoding = "__none__"
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    560,
    993,
    358,
]
dropout = 0.061388060079561706

[model.autodis]
n_meta_embeddings = 152
temperature = 1.2908698727303594

[training]
batch_size = 128
lr = 0.00025755453440399546
weight_decay = 1.6116317866103822e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
