seed = 11

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    798,
    451,
    451,
    451,
    475,
]
dropout = 0.20993662310331682

[training]
batch_size = 1024
lr = 0.0034207636876420334
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 117
subsample = "__none__"

[bins.tree]
min_samples_leaf = 58
min_impurity_decrease = 1.1676363631031303e-05
