seed = 10
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 106
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    766,
]
dropout = 0.06445379195581596

[model.positional_encoding]
n = 123
sigma = 19.178816383731053
trainable = true
initialization = "normal"

[training]
batch_size = 128
lr = 0.003844982988384105
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
