seed = 5

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 126
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 8
d_main = 225
dropout_first = 0.2987193040111581
dropout_second = 0.14771419232772237
d_hidden = 359

[training]
batch_size = 128
lr = 6.112629428402705e-05
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 253
subsample = "__none__"

[bins.tree]
min_samples_leaf = 57
min_impurity_decrease = 0.000384762795890823
