seed = 0

[data]
path = "data/california"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 472
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 3
attention_dropout = 0.30083449085441194
ffn_dropout = 0.3436543405723867
ffn_d_hidden = 1162

[training]
batch_size = 256
lr = 0.0003230033103143712
weight_decay = 6.96868865649607e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 234
subsample = "__none__"

[bins.tree]
min_samples_leaf = 14
min_impurity_decrease = 0.0003922834978189732
