seed = 4

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    221,
]
dropout = 0.0

[training]
batch_size = 128
lr = 0.0015131496560867618
weight_decay = 0.000331481914677374
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 135
subsample = "__none__"

[bins.tree]
min_samples_leaf = 32
min_impurity_decrease = 0.00031578850325804364
