seed = 1
bins = "__none__"

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 280
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 1
attention_dropout = 0.17336913159928752
ffn_dropout = 0.18117488264673248
ffn_d_hidden = 296

[training]
batch_size = 256
lr = 9.520710849203389e-05
weight_decay = 8.79039870833683e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
