seed = 10

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 117
num_embedding_arch = [
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.mlp]
d_layers = [
    805,
]
dropout = 0.41377715958684885

[training]
batch_size = 512
lr = 0.00013026312023717236
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 179
subsample = "__none__"

[bins.tree]
min_samples_leaf = 17
min_impurity_decrease = 2.0813723176389746e-05
