seed = 3

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.resnet]
n_blocks = 6
d_main = 74
dropout_first = 0.4075492949644828
dropout_second = 0.0
d_hidden = 261

[training]
batch_size = 128
lr = 0.0016744367551643218
weight_decay = 1.030139833123239e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 3
tree = "__none__"
subsample = "__none__"
