seed = 14

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
positional_encoding = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    969,
    542,
]
dropout = 0.0

[training]
batch_size = 128
lr = 0.0017678173145744063
weight_decay = 1.1385953381489417e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 159
encoding = "one-blob"
one_blob_gamma = 0.6256837783419192
subsample = "__none__"

[bins.tree]
min_samples_leaf = 79
min_impurity_decrease = 0.004038653086453455
