seed = 0

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 114
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 8
d_main = 147
dropout_first = 0.384476029995364
dropout_second = 0.0
d_hidden = 389

[training]
batch_size = 1024
lr = 0.003229874194038976
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 191
subsample = "__none__"

[bins.tree]
min_samples_leaf = 17
min_impurity_decrease = 1.8718719743063427e-05
