seed = 0
bins = "__none__"

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    668,
    424,
    424,
    424,
    317,
]
dropout = 0.0

[model.fourier_features]
n = 327
sigma = 0.8007138793386054

[training]
batch_size = 128
lr = 0.00033952421962104505
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
