seed = 13

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
positional_encoding = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    849,
    617,
    617,
    721,
]
dropout = 0.0

[training]
batch_size = 128
lr = 0.0008438339950661695
weight_decay = 1.6339553715305367e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 198
encoding = "one-blob"
one_blob_gamma = 1.9945097857381864
subsample = "__none__"

[bins.tree]
min_samples_leaf = 88
min_impurity_decrease = 0.0003395043583564294
