seed = 5

[data]
path = "data/microsoft"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 52
num_embedding_arch = [
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.mlp]
d_layers = [
    480,
    204,
    247,
]
dropout = 0.14656258815896736

[training]
batch_size = 1024
lr = 0.00027431639674840006
weight_decay = 1.7698957842368494e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 2
subsample = "__none__"

[bins.tree]
min_samples_leaf = 109
min_impurity_decrease = 1.3494402763425424e-08
