seed = 8
bins = "__none__"

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 208
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.transformer]
residual_dropout = 0.0
n_blocks = 3
attention_dropout = 0.1735526850948136
ffn_dropout = 0.05681850857689891
ffn_d_hidden = 533

[model.positional_encoding]
n = 46
sigma = 0.07143620317143423
trainable = true
initialization = "normal"

[training]
batch_size = 512
lr = 1.2723111039127136e-05
weight_decay = 1e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
