seed = 14
bins = "__none__"

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 1
d_main = 114
dropout_first = 0.4542357951018456
dropout_second = 0.15487558840460453
d_hidden = 206

[model.positional_encoding]
n = 3
sigma = 0.01949377836214516
trainable = true
initialization = "normal"

[training]
batch_size = 512
lr = 0.00023461285447673374
weight_decay = 0.0009804358888684797
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
