seed = 8

[data]
path = "data/adult"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    514,
]
dropout = 0.3532549625407062

[training]
batch_size = 256
lr = 0.00023159252029092514
weight_decay = 1.0048790205871336e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 47
subsample = "__none__"

[bins.tree]
min_samples_leaf = 7
min_impurity_decrease = 2.165506769614725e-06
