seed = 10

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 30
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 7
d_main = 456
dropout_first = 0.3805320059265692
dropout_second = 0.0
d_hidden = 1629

[training]
batch_size = 128
lr = 0.003835043685426313
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 79
subsample = "__none__"

[bins.tree]
min_samples_leaf = 125
min_impurity_decrease = 0.0002870671213297444
