seed = 0

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    698,
]
dropout = 0.0

[training]
batch_size = 1024
lr = 9.666017513662909e-05
weight_decay = 3.21151266438695e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 91
value = "one"
tree = "__none__"
subsample = "__none__"
