seed = 11

[data]
path = "data/microsoft"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 38
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 6
d_main = 74
dropout_first = 0.44651753697456925
dropout_second = 0.10775051227904933
d_hidden = 220

[training]
batch_size = 1024
lr = 0.0011832794077971632
weight_decay = 0.00019376885819632963
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 183
subsample = "__none__"

[bins.tree]
min_samples_leaf = 17
min_impurity_decrease = 0.006962654355194945
