seed = 0

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 28
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.mlp]
d_layers = [
    928,
    824,
]
dropout = 0.135247434442047

[training]
batch_size = 128
lr = 0.004447442379368036
weight_decay = 3.600714297233922e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 172
subsample = "__none__"

[bins.tree]
min_samples_leaf = 35
min_impurity_decrease = 0.0005347286592814264
