seed = 13

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 424
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 3
attention_dropout = 0.4465643916994285
ffn_dropout = 0.3798723182978342
ffn_d_hidden = 850

[training]
batch_size = 512
lr = 0.00016427845420544858
weight_decay = 1e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 193
subsample = "__none__"

[bins.tree]
min_samples_leaf = 57
min_impurity_decrease = 9.379342412557048e-05
