seed = 13
bins = "__none__"

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    302,
    521,
]
dropout = 0.06830087721306224

[model.positional_encoding]
n = 67
sigma = 0.0012894238766067152
trainable = false
initialization = "log-linear"

[training]
batch_size = 128
lr = 6.227983595252287e-05
weight_decay = 0.0007711743382295523
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
