seed = 1
bins = "__none__"

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 4
d_main = 249
dropout_first = 0.27890478771786925
dropout_second = 0.24112781041498046
d_hidden = 504

[model.positional_encoding]
n = 68
sigma = 18.193177890649118
trainable = false
initialization = "log-linear"

[training]
batch_size = 128
lr = 0.0019945931495708746
weight_decay = 1.308639776420192e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
