seed = 6
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 56
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 5
d_main = 193
dropout_first = 0.12178635926150828
dropout_second = 0.0
d_hidden = 377

[model.positional_encoding]
n = 125
sigma = 13.729732640446368
trainable = false
initialization = "log-linear"

[training]
batch_size = 128
lr = 0.0018874792671395798
weight_decay = 5.851228279771955e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
