seed = 13

[data]
path = "data/california"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 78
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    345,
    646,
    646,
    357,
]
dropout = 0.4325036232895139

[training]
batch_size = 256
lr = 0.0004435452499319372
weight_decay = 4.384452305146571e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
