seed = 0

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 440
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 3
attention_dropout = 0.1326055170996284
ffn_dropout = 0.2734522215140842
ffn_d_hidden = 1129

[training]
batch_size = 512
lr = 1.7658724424772542e-05
weight_decay = 6.995584221676623e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 246
subsample = "__none__"

[bins.tree]
min_samples_leaf = 77
min_impurity_decrease = 0.007472222072009748
