seed = 8

[data]
path = "data/adult"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 95
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    297,
    464,
    464,
    464,
    464,
    464,
    867,
]
dropout = 0.48448547662506697

[training]
batch_size = 256
lr = 8.561256559514397e-05
weight_decay = 2.424928241011557e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
