seed = 7
bins = "__none__"

[data]
path = "data/microsoft"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 76
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 6
d_main = 260
dropout_first = 0.23267452234644406
dropout_second = 0.4072674227101546
d_hidden = 312

[model.positional_encoding]
n = 105
sigma = 0.0017373408807492855
trainable = false
initialization = "log-linear"

[training]
batch_size = 1024
lr = 0.00020949614421979682
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
