seed = 13
bins = "__none__"

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 80
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    609,
]
dropout = 0.22342391339819045

[model.positional_encoding]
n = 32
sigma = 0.007520393523519177
trainable = true
initialization = "log-linear"

[training]
batch_size = 128
lr = 0.00010362498693350477
weight_decay = 0.0006562151564095189
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
