seed = 6
bins = "__none__"

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 8
d_main = 71
dropout_first = 0.16639906973125335
dropout_second = 0.0
d_hidden = 97

[model.positional_encoding]
n = 1
sigma = 0.07093907831779954
trainable = true
initialization = "normal"

[training]
batch_size = 256
lr = 0.0007916460319721985
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
