seed = 4
bins = "__none__"

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 34
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    366,
]
dropout = 0.2992001230611018

[model.positional_encoding]
n = 111
sigma = 0.002805921738758945
trainable = true
initialization = "log-linear"

[training]
batch_size = 512
lr = 0.00016428050234695716
weight_decay = 2.060349905227705e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
