seed = 6

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 57
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 2
d_main = 309
dropout_first = 0.01367589022379358
dropout_second = 0.0
d_hidden = 957

[training]
batch_size = 128
lr = 0.000329547098409887
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 112
subsample = "__none__"

[bins.tree]
min_samples_leaf = 114
min_impurity_decrease = 0.000405788148676825
