seed = 7
bins = "__none__"

[data]
path = "data/california"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 7
d_main = 48
dropout_first = 0.30370668532295775
dropout_second = 0.0
d_hidden = 83

[model.positional_encoding]
n = 27
sigma = 0.023431410097955265
trainable = false
initialization = "log-linear"

[training]
batch_size = 256
lr = 0.0006904388886314246
weight_decay = 2.1977258437999133e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
