seed = 2
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    955,
    760,
    760,
    760,
    76,
]
dropout = 0.08071985082008852

[model.fourier_features]
n = 907
sigma = 0.03929502740492392

[training]
batch_size = 128
lr = 0.000340514452015143
weight_decay = 1.1857094660026628e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
