seed = 11
bins = "__none__"

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 288
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 4
attention_dropout = 0.1363152596402798
ffn_dropout = 0.014328560045563925
ffn_d_hidden = 698

[training]
batch_size = 128
lr = 3.0174775218058505e-05
weight_decay = 1.9589827873812647e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
