seed = 5
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 123
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    996,
    622,
]
dropout = 0.21924450468072562

[model.positional_encoding]
n = 83
sigma = 30.842848518848
trainable = false
initialization = "log-linear"

[training]
batch_size = 128
lr = 0.004519772614059779
weight_decay = 1.0193233419040544e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
