seed = 14

[data]
path = "data/covtype"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 100
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    77,
    657,
    657,
    657,
    657,
    749,
]
dropout = 0.0

[training]
batch_size = 1024
lr = 0.00184129009541315
weight_decay = 2.1594965121061625e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
