seed = 0

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 296
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 3
attention_dropout = 0.20394648944212274
ffn_dropout = 0.165787334718615
ffn_d_hidden = 750

[training]
batch_size = 128
lr = 0.00035815663551192216
weight_decay = 1.5913700651349108e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 102
subsample = "__none__"

[bins.tree]
min_samples_leaf = 105
min_impurity_decrease = 0.00027049989680506716
