seed = 7
bins = "__none__"

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 4
d_main = 101
dropout_first = 0.1460187114687218
dropout_second = 0.13259519651609816
d_hidden = 108

[model.positional_encoding]
n = 107
sigma = 0.012858837830710174
trainable = false
initialization = "log-linear"

[training]
batch_size = 256
lr = 6.550461095827379e-05
weight_decay = 0.0009947219948950895
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
