seed = 5

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 72
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 2
d_main = 82
dropout_first = 0.10890092112606328
dropout_second = 0.01911762873601522
d_hidden = 206

[training]
batch_size = 256
lr = 0.0017096661769420353
weight_decay = 0.00015397758018073288
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 201
subsample = "__none__"

[bins.tree]
min_samples_leaf = 58
min_impurity_decrease = 0.009776326714595515
