seed = 10

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 97
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    1015,
    449,
    449,
    449,
    337,
]
dropout = 0.1348275009827335

[training]
batch_size = 256
lr = 0.0009315289779125191
weight_decay = 1.7980388704556122e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
