seed = 1

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 77
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    933,
    837,
]
dropout = 0.3991633670251851

[training]
batch_size = 512
lr = 0.0006791409312807271
weight_decay = 0.00012147758203368532
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
