seed = 3

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 77
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    526,
    311,
    311,
    311,
    826,
]
dropout = 0.43969163265677097

[training]
batch_size = 512
lr = 0.0003624567212581622
weight_decay = 0.0001525021892952668
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
