seed = 14

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 124
num_embedding_arch = [
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    488,
]
dropout = 0.42275359953448316

[training]
batch_size = 512
lr = 0.000180721699506457
weight_decay = 9.548943410499024e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
