seed = 9
bins = "__none__"

[data]
path = "data/covtype"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 6
d_main = 347
dropout_first = 0.44322128366812813
dropout_second = 0.33185938175358803
d_hidden = 712

[model.positional_encoding]
n = 13
sigma = 1.2991734218244704
trainable = true
initialization = "normal"

[training]
batch_size = 1024
lr = 0.00015270003676769997
weight_decay = 0.0004854561681403626
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
