seed = 1

[data]
path = "data/otto"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 62
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 5
d_main = 475
dropout_first = 0.49672360977340235
dropout_second = 0.0
d_hidden = 1308

[training]
batch_size = 512
lr = 0.00015026001873855502
weight_decay = 0.0008249459905703267
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 76
tree = "__none__"
subsample = "__none__"
