seed = 12
bins = "__none__"

[data]
path = "data/covtype"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 12
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 6
d_main = 329
dropout_first = 0.39364142858438955
dropout_second = 0.0
d_hidden = 616

[model.positional_encoding]
n = 73
sigma = 0.019664752155553442
trainable = true
initialization = "log-linear"

[training]
batch_size = 1024
lr = 7.55916058944447e-05
weight_decay = 1.023800563575064e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
