seed = 13

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 59
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.mlp]
d_layers = [
    179,
    410,
]
dropout = 0.0

[training]
batch_size = 1024
lr = 0.00028609130460919766
weight_decay = 8.051406509896416e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 55
subsample = "__none__"

[bins.tree]
min_samples_leaf = 68
min_impurity_decrease = 1.1727112400543234e-05
