seed = 6
bins = "__none__"

[data]
path = "data/covtype"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 95
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    599,
    868,
    868,
    868,
    868,
    247,
]
dropout = 0.14635120090662296

[model.positional_encoding]
n = 53
sigma = 0.014729954125093533
trainable = false
initialization = "log-linear"

[training]
batch_size = 1024
lr = 0.0008711620432498535
weight_decay = 0.0007903741739122797
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
