seed = 11
bins = "__none__"

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 63
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 1
d_main = 412
dropout_first = 0.4989290860907673
dropout_second = 0.24349929544838747
d_hidden = 1525

[model.positional_encoding]
n = 67
sigma = 0.0012730373918552486
trainable = false
initialization = "log-linear"

[training]
batch_size = 1024
lr = 0.0036511346726956794
weight_decay = 0.00023541372639079416
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
