seed = 14

[data]
path = "data/adult"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
positional_encoding = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    435,
    104,
    104,
    104,
    104,
    104,
    104,
    44,
]
dropout = 0.25644583310428987

[training]
batch_size = 256
lr = 7.639383193155531e-05
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 34
encoding = "one-blob"
one_blob_gamma = 1.8846774917516107
subsample = "__none__"

[bins.tree]
min_samples_leaf = 8
min_impurity_decrease = 5.060682225103441e-07
