seed = 7
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 46
num_embedding_arch = [
    "positional",
    "linear",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    998,
    690,
]
dropout = 0.0019001161380328927

[model.positional_encoding]
n = 63
sigma = 11.752208390515277
trainable = true
initialization = "normal"

[training]
batch_size = 128
lr = 0.003994660903555985
weight_decay = 1.0727969022300632e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
