seed = 5
bins = "__none__"

[data]
path = "data/covtype"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 8
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    335,
    917,
    917,
    917,
    84,
]
dropout = 0.17773735184608258

[model.positional_encoding]
n = 120
sigma = 0.06904307145256995
trainable = false
initialization = "log-linear"

[training]
batch_size = 1024
lr = 0.00010516611713838248
weight_decay = 1.72518415682529e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
