seed = 14

[data]
path = "data/higgs-small"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[xgboost]
booster = "gbtree"
n_estimators = 2000
n_jobs = 1
tree_method = "gpu_hist"
colsample_bytree = 0.5827711509052577
gamma = 0
lambda = 0.0
learning_rate = 0.040461445864863624
max_depth = 10
min_child_weight = 18.684278471418498
subsample = 0.9950119817995908

[xgboost_fit]
early_stopping_rounds = 50
verbose = true
