seed = 5

[data]
path = "data/california"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 264
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 4
attention_dropout = 0.27105269303598245
ffn_dropout = 0.05305387816380375
ffn_d_hidden = 648

[training]
batch_size = 256
lr = 3.945104960619535e-05
weight_decay = 2.919632706370366e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 149
subsample = "__none__"

[bins.tree]
min_samples_leaf = 20
min_impurity_decrease = 0.0005115083608590613
