seed = 7

[data]
path = "data/adult"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 128
num_embedding_arch = [
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.mlp]
d_layers = [
    419,
    954,
]
dropout = 0.4718912866879653

[training]
batch_size = 256
lr = 5.152234033289498e-05
weight_decay = 2.2429615218018807e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 24
subsample = "__none__"

[bins.tree]
min_samples_leaf = 3
min_impurity_decrease = 1.5921184091189173e-07
