seed = 5

[data]
path = "data/otto"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 74
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    856,
    72,
    564,
]
dropout = 0.4878260532840904

[training]
batch_size = 512
lr = 0.0004177988916512021
weight_decay = 0.000374139241328216
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
