seed = 4

[data]
path = "data/california"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 80
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 6
d_main = 63
dropout_first = 0.3045909929864416
dropout_second = 0.0
d_hidden = 172

[training]
batch_size = 256
lr = 0.0028221150760128345
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 191
tree = "__none__"
subsample = "__none__"
