seed = 11
bins = "__none__"

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 61
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 1
d_main = 390
dropout_first = 0.3402854924100254
dropout_second = 0.0
d_hidden = 1360

[model.positional_encoding]
n = 97
sigma = 0.19224439694734527
trainable = true
initialization = "normal"

[training]
batch_size = 512
lr = 0.0001748227606667588
weight_decay = 5.518253765840126e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
