seed = 3

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    710,
    158,
    158,
    158,
    158,
    733,
]
dropout = 0.09601518112491808

[training]
batch_size = 256
lr = 0.0001478492550930103
weight_decay = 1.0225378316427606e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 236
value = "one"
subsample = "__none__"

[bins.tree]
min_samples_leaf = 97
min_impurity_decrease = 2.201205676665487e-09
