seed = 2

[data]
path = "data/synthetic/oblivious_forest_10000_16_6"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 4
depth = 10

[catboost_fit]
logging_level = "Verbose"
