seed = 8

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 42
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    870,
    814,
    176,
]
dropout = 0.30963016875813076

[training]
batch_size = 512
lr = 0.00037938647709944454
weight_decay = 1.583089592819181e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
