seed = 2

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    892,
    581,
    302,
]
dropout = 0.39215021090249064

[training]
batch_size = 128
lr = 0.00013385148494449647
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 183
subsample = "__none__"

[bins.tree]
min_samples_leaf = 59
min_impurity_decrease = 1.4725145647508068e-07
