seed = 0
bins = "__none__"

[data]
path = "data/california"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    118,
    1021,
    1021,
    1021,
    1021,
    1021,
    1021,
    538,
]
dropout = 0.18144472478720874

[model.positional_encoding]
n = 44
sigma = 0.09202815982926647
trainable = true
initialization = "normal"

[training]
batch_size = 256
lr = 0.00023862454110406078
weight_decay = 0.00013555214137647237
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
