seed = 12

[data]
path = "data/santander"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 4
bagging_temperature = 0.005925406827771457
depth = 3
l2_leaf_reg = 7.9128702747428425
leaf_estimation_iterations = 1
learning_rate = 0.22595290272446578

[catboost_fit]
logging_level = "Verbose"
