seed = 14
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    901,
    541,
    624,
]
dropout = 0.4718646553461543

[model.positional_encoding]
n = 123
sigma = 99.10361346916979
trainable = false
initialization = "log-linear"

[training]
batch_size = 128
lr = 0.0005000021266367761
weight_decay = 0.0006351389893432688
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
