seed = 8

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 29
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.resnet]
n_blocks = 2
d_main = 512
dropout_first = 0.41862238995287343
dropout_second = 0.0
d_hidden = 685

[training]
batch_size = 512
lr = 0.0004078865114103079
weight_decay = 1.1554376140837454e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
