seed = 6

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    754,
    823,
    823,
    771,
]
dropout = 0.0

[training]
batch_size = 1024
lr = 0.0031222603823036713
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 249
value = "one"
subsample = "__none__"

[bins.tree]
min_samples_leaf = 23
min_impurity_decrease = 1.204410815320933e-05
