seed = 8
bins = "__none__"

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 3
num_embedding_arch = [
    "positional",
    "linear",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    163,
    916,
]
dropout = 0.4550208810073734

[model.positional_encoding]
n = 24
sigma = 0.01584361785177209
trainable = true
initialization = "normal"

[training]
batch_size = 512
lr = 0.00010943316207544324
weight_decay = 0.0003203505844203177
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
