seed = 5
bins = "__none__"

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    224,
    896,
    284,
]
dropout = 0.0

[model.fourier_features]
n = 457
sigma = 0.07462754087905646

[training]
batch_size = 1024
lr = 6.98710653756454e-05
weight_decay = 4.953722691366476e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
