seed = 14

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    531,
]
dropout = 0.42846743285199274

[training]
batch_size = 128
lr = 0.0011839825024890418
weight_decay = 3.811069217221721e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 11
value = "one"
tree = "__none__"
subsample = "__none__"
