seed = 0

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.resnet]
n_blocks = 4
d_main = 152
dropout_first = 0.35119208714957
dropout_second = 0.0
d_hidden = 329

[training]
batch_size = 128
lr = 0.0037381120129007937
weight_decay = 2.394599129383567e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
