seed = 4

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    164,
]
dropout = 0.19796070060637036

[training]
batch_size = 512
lr = 7.62580313777908e-05
weight_decay = 3.406421266659774e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 70
tree = "__none__"
subsample = "__none__"
