seed = 0

[data]
path = "data/otto"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 111
num_embedding_arch = [
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.mlp]
d_layers = [
    980,
    517,
]
dropout = 0.41693662867530457

[training]
batch_size = 512
lr = 0.00043286194606532524
weight_decay = 2.8076514451140252e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 255
subsample = "__none__"

[bins.tree]
min_samples_leaf = 103
min_impurity_decrease = 1.066442945162716e-07
