seed = 7

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    973,
]
dropout = 0.3547367715287102

[training]
batch_size = 512
lr = 6.901848719606059e-05
weight_decay = 1.5619427947917663e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 56
value = "one"
subsample = "__none__"

[bins.tree]
min_samples_leaf = 94
min_impurity_decrease = 1.6879834288280566e-08
