seed = 11
bins = "__none__"

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 33
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    896,
    889,
    889,
    889,
    929,
]
dropout = 0.26248997159670645

[model.positional_encoding]
n = 103
sigma = 1.210520290416288
trainable = true
initialization = "log-linear"

[training]
batch_size = 128
lr = 0.00021597769620892776
weight_decay = 0.0005734291393672846
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
