seed = 3

[data]
path = "data/microsoft"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.resnet]
n_blocks = 4
d_main = 373
dropout_first = 0.43021810519909426
dropout_second = 0.0
d_hidden = 418

[training]
batch_size = 1024
lr = 0.0007324632783173967
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 2
subsample = "__none__"

[bins.tree]
min_samples_leaf = 107
min_impurity_decrease = 0.0011744049015618024
