seed = 2
bins = "__none__"

[data]
path = "data/adult"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 84
num_embedding_arch = [
    "autodis",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
positional_encoding = "__none__"
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    611,
    195,
    195,
    195,
    195,
    923,
]
dropout = 0.0

[model.autodis]
n_meta_embeddings = 237
temperature = 3.4177021326253723

[training]
batch_size = 256
lr = 0.0002698728225166345
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
