seed = 13

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    544,
    940,
    940,
    940,
    940,
    940,
    915,
]
dropout = 0.28464418987137524

[training]
batch_size = 128
lr = 0.00038863780613199763
weight_decay = 2.1953436380470722e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 20
subsample = "__none__"

[bins.tree]
min_samples_leaf = 17
min_impurity_decrease = 0.0026081658199447414
