seed = 2
bins = "__none__"

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 118
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 3
d_main = 302
dropout_first = 0.20029685299968175
dropout_second = 0.0
d_hidden = 1087

[model.positional_encoding]
n = 100
sigma = 0.0027424837606062017
trainable = false
initialization = "log-linear"

[training]
batch_size = 512
lr = 0.003080256815079834
weight_decay = 2.3317677166142645e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
