seed = 13

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 41
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.mlp]
d_layers = [
    479,
    252,
    252,
    252,
    252,
    252,
    507,
]
dropout = 0.0

[training]
batch_size = 256
lr = 0.0006065049298975076
weight_decay = 1.1630260938801798e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 70
subsample = "__none__"

[bins.tree]
min_samples_leaf = 73
min_impurity_decrease = 0.009960934680597302
