seed = 10
bins = "__none__"

[data]
path = "data/covtype"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    268,
    933,
    933,
    933,
    845,
]
dropout = 0.07376303115778152

[model.positional_encoding]
n = 6
sigma = 0.5429791747031727
trainable = true
initialization = "normal"

[training]
batch_size = 1024
lr = 0.000536200565904071
weight_decay = 0.0009711528392339118
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
