seed = 5
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 512
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 4
attention_dropout = 0.10800966306496418
ffn_dropout = 0.2506330415161669
ffn_d_hidden = 839

[training]
batch_size = 128
lr = 0.00013519000604951404
weight_decay = 1.8584069850613815e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
