seed = 11

[data]
path = "data/churn"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 4
bagging_temperature = 0.494829656619226
depth = 7
l2_leaf_reg = 7.099726456429875
leaf_estimation_iterations = 7
learning_rate = 0.10970538862057026

[catboost_fit]
logging_level = "Verbose"
