seed = 9

[data]
path = "data/adult"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"

[xgboost]
booster = "gbtree"
n_estimators = 2000
n_jobs = 1
tree_method = "gpu_hist"
colsample_bytree = 0.9671610859466809
gamma = 0.5845844308462009
lambda = 0.26526626011784094
learning_rate = 0.22500826376176813
max_depth = 4
min_child_weight = 0.15563555065536416
subsample = 0.9356806806386753

[xgboost_fit]
early_stopping_rounds = 50
verbose = true
