seed = 1
bins = "__none__"

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 67
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    915,
    483,
    483,
    51,
]
dropout = 0.4322377875963865

[model.positional_encoding]
n = 113
sigma = 0.019023926383124667
trainable = true
initialization = "normal"

[training]
batch_size = 512
lr = 0.0005647654878705231
weight_decay = 0.00036609532725076277
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
