seed = 3

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 432
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 2
attention_dropout = 0.16004455663620512
ffn_dropout = 0.0006048247502242754
ffn_d_hidden = 980

[training]
batch_size = 512
lr = 1.7128152674906144e-05
weight_decay = 1e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 247
subsample = "__none__"

[bins.tree]
min_samples_leaf = 68
min_impurity_decrease = 0.0009181994561768504
