seed = 11
bins = "__none__"

[data]
path = "data/fb-comments"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 36
num_embedding_arch = [
    "positional",
    "linear",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    589,
    963,
    628,
]
dropout = 0.06164393505113096

[model.positional_encoding]
n = 31
sigma = 0.7422826745901961
trainable = true
initialization = "normal"

[training]
batch_size = 512
lr = 0.00019202578931631033
weight_decay = 2.9193898978012513e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
