seed = 5
bins = "__none__"

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 128
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.transformer]
residual_dropout = 0.0
n_blocks = 1
attention_dropout = 0.12311946749960981
ffn_dropout = 0.2090261989269185
ffn_d_hidden = 277

[model.positional_encoding]
n = 117
sigma = 0.04114103718590486
trainable = true
initialization = "normal"

[training]
batch_size = 256
lr = 8.831247441615196e-05
weight_decay = 1.7596156364055376e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
