seed = 12

[data]
path = "data/adult"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 4
bagging_temperature = 0.19842642056648427
depth = 9
l2_leaf_reg = 8.295078018890539
leaf_estimation_iterations = 2
learning_rate = 0.041103142163271704

[catboost_fit]
logging_level = "Verbose"
