seed = 5

[data]
path = "data/covtype"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    281,
    783,
    783,
    783,
    524,
]
dropout = 0.04819585741177791

[training]
batch_size = 1024
lr = 7.207506713304263e-05
weight_decay = 4.066063728848985e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 51
subsample = "__none__"

[bins.tree]
min_samples_leaf = 51
min_impurity_decrease = 4.0333464638846734e-05
