seed = 7

[data]
path = "data/microsoft"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.resnet]
n_blocks = 8
d_main = 510
dropout_first = 0.47864905716667233
dropout_second = 0.20208873598179636
d_hidden = 883

[training]
batch_size = 1024
lr = 0.0030057851412381023
weight_decay = 0.00015749663464866158
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
