seed = 7

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 296
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 2
attention_dropout = 0.43281786139426653
ffn_dropout = 0.4172170368413529
ffn_d_hidden = 456

[training]
batch_size = 1024
lr = 2.8958806659647515e-05
weight_decay = 1e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 160
subsample = "__none__"

[bins.tree]
min_samples_leaf = 73
min_impurity_decrease = 6.687304955956112e-06
