seed = 1
bins = "__none__"

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    613,
    593,
    593,
    593,
    241,
]
dropout = 0.0

[model.positional_encoding]
n = 109
sigma = 3.1433763157634242
trainable = false
initialization = "log-linear"

[training]
batch_size = 128
lr = 0.0001967179119875214
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
