seed = 14

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 200
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 2
attention_dropout = 0.00367871295345849
ffn_dropout = 0.37862817334855475
ffn_d_hidden = 474

[training]
batch_size = 256
lr = 1.5183749356168051e-05
weight_decay = 9.993813535779618e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 187
subsample = "__none__"

[bins.tree]
min_samples_leaf = 91
min_impurity_decrease = 0.0040954184929496585
