seed = 0

[data]
path = "data/eye"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[xgboost]
booster = "gbtree"
n_estimators = 2000
n_jobs = 1
tree_method = "gpu_hist"
colsample_bytree = 0.5323514820100446
gamma = 0.01246195791974756
lambda = 0.0
learning_rate = 0.059825591324653676
max_depth = 10
min_child_weight = 0.08437781929639679
subsample = 0.9525470398593069

[xgboost_fit]
early_stopping_rounds = 50
verbose = true
