seed = 7

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    548,
    754,
    754,
    931,
]
dropout = 0.24680695206760359

[training]
batch_size = 128
lr = 0.0021648904617639093
weight_decay = 0.0001223826571948112
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
