seed = 8
bins = "__none__"

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 73
num_embedding_arch = [
    "autodis",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
positional_encoding = "__none__"
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    87,
    103,
    103,
    103,
    103,
    103,
    103,
    36,
]
dropout = 0.0

[model.autodis]
n_meta_embeddings = 223
temperature = 7.08481306320402

[training]
batch_size = 128
lr = 0.001982837540885505
weight_decay = 2.263722969739549e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
