seed = 13
bins = "__none__"

[data]
path = "data/covtype"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 7
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    939,
    689,
    689,
    689,
    689,
    689,
    691,
]
dropout = 0.3258929495263485

[model.positional_encoding]
n = 107
sigma = 1.6434072231701713
trainable = true
initialization = "normal"

[training]
batch_size = 1024
lr = 0.0001094187426642657
weight_decay = 1.792009293851349e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
