seed = 0
bins = "__none__"

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 111
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 1
d_main = 442
dropout_first = 0.03347113274460268
dropout_second = 0.0
d_hidden = 1338

[model.positional_encoding]
n = 1
sigma = 1.452709217913318
trainable = true
initialization = "normal"

[training]
batch_size = 128
lr = 0.000530352771215654
weight_decay = 1.3080228173302565e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
