seed = 1
bins = "__none__"

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 75
num_embedding_arch = [
    "positional",
    "linear",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    878,
    277,
    277,
    277,
    973,
]
dropout = 0.1378589163932148

[model.positional_encoding]
n = 104
sigma = 2.9502687893546042
trainable = true
initialization = "normal"

[training]
batch_size = 128
lr = 0.000730022922069269
weight_decay = 0.0003311454318158413
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
