seed = 4

[data]
path = "data/adult"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 124
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 8
d_main = 490
dropout_first = 0.3373487303738271
dropout_second = 0.4266444012048564
d_hidden = 1856

[training]
batch_size = 256
lr = 0.004381116257974785
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 255
subsample = "__none__"

[bins.tree]
min_samples_leaf = 45
min_impurity_decrease = 1.869650825573891e-09
