seed = 10

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    895,
    511,
    511,
    511,
    896,
]
dropout = 0.2809018459056341

[training]
batch_size = 256
lr = 0.00019279967621204348
weight_decay = 2.4361000218604e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 213
subsample = "__none__"

[bins.tree]
min_samples_leaf = 114
min_impurity_decrease = 0.0027642001527785785
