seed = 14

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 62
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.resnet]
n_blocks = 5
d_main = 464
dropout_first = 0.47600875287482936
dropout_second = 0.0
d_hidden = 512

[training]
batch_size = 512
lr = 0.00020440949409405347
weight_decay = 8.001059126208773e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
