seed = 0
bins = "__none__"

[data]
path = "data/otto"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 102
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 3
d_main = 427
dropout_first = 0.32673416453479526
dropout_second = 0.41723115274658534
d_hidden = 617

[model.positional_encoding]
n = 113
sigma = 0.9551456881045758
trainable = false
initialization = "log-linear"

[training]
batch_size = 512
lr = 7.257090377000548e-05
weight_decay = 6.2491054423163525e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
