seed = 5

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 472
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 4
attention_dropout = 0.25506930663234406
ffn_dropout = 0.4449647419307462
ffn_d_hidden = 1149

[training]
batch_size = 128
lr = 0.00010492696098520185
weight_decay = 2.709740887348595e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 187
subsample = "__none__"

[bins.tree]
min_samples_leaf = 115
min_impurity_decrease = 5.741337101222355e-07
