seed = 2
bins = "__none__"

[data]
path = "data/covtype"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    131,
    993,
    993,
    993,
    993,
    993,
    940,
]
dropout = 0.0

[model.positional_encoding]
n = 117
sigma = 0.02572546755535266
trainable = false
initialization = "log-linear"

[training]
batch_size = 1024
lr = 0.000543137030988786
weight_decay = 0.0004984849649983101
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
