seed = 13

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
positional_encoding = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    801,
]
dropout = 0.18511507954437684

[training]
batch_size = 128
lr = 0.0011603178200565564
weight_decay = 1.5295042327488062e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 30
encoding = "one-blob"
one_blob_gamma = 1.060862120561218
tree = "__none__"
subsample = "__none__"
