seed = 11
bins = "__none__"

[data]
path = "data/otto"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 7
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 1
d_main = 303
dropout_first = 0.18261671230084464
dropout_second = 0.30690940327054067
d_hidden = 704

[model.positional_encoding]
n = 59
sigma = 0.9581158069711155
trainable = true
initialization = "log-linear"

[training]
batch_size = 512
lr = 7.500335958722588e-05
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
