seed = 7

[data]
path = "data/california"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 48
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 3
d_main = 123
dropout_first = 0.2539758318914756
dropout_second = 0.0
d_hidden = 283

[training]
batch_size = 256
lr = 7.906230799944287e-05
weight_decay = 8.291133858816321e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 89
subsample = "__none__"

[bins.tree]
min_samples_leaf = 101
min_impurity_decrease = 0.0005471863635572689
