seed = 14

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 10
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.resnet]
n_blocks = 7
d_main = 510
dropout_first = 0.22382099977366915
dropout_second = 0.03625265902021971
d_hidden = 741

[training]
batch_size = 128
lr = 0.0016031388986318983
weight_decay = 5.5870695620880175e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 98
tree = "__none__"
subsample = "__none__"
