seed = 4

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 208
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
mlp = "__none__"
resnet = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.transformer]
residual_dropout = 0.0
n_blocks = 3
attention_dropout = 0.12681384788645744
ffn_dropout = 0.18798395938560986
ffn_d_hidden = 303

[training]
batch_size = 256
lr = 8.810420494856094e-05
weight_decay = 3.431315359487309e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 203
tree = "__none__"
subsample = "__none__"
