seed = 1

[data]
path = "data/santander"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[xgboost]
booster = "gbtree"
n_estimators = 2000
n_jobs = 1
tree_method = "gpu_hist"
colsample_bytree = 0.7790992908124852
gamma = 0
lambda = 0.0
learning_rate = 0.06901186763011359
max_depth = 4
min_child_weight = 0.38205778911352256
subsample = 0.9385059434669933

[xgboost_fit]
early_stopping_rounds = 50
verbose = true
