seed = 12

[data]
path = "data/otto"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    872,
    225,
]
dropout = 0.48611953902494215

[training]
batch_size = 512
lr = 0.00010102047206391853
weight_decay = 0.0005977089186014641
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 41
subsample = "__none__"

[bins.tree]
min_samples_leaf = 105
min_impurity_decrease = 6.55603554918751e-05
