seed = 3
bins = "__none__"

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    860,
    326,
    326,
    326,
    150,
]
dropout = 0.0

[model.positional_encoding]
n = 91
sigma = 0.0853388298514902
trainable = true
initialization = "normal"

[training]
batch_size = 256
lr = 0.000339316327501057
weight_decay = 1.1811110533418445e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
