seed = 5

[data]
path = "data/churn"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"

[xgboost]
booster = "gbtree"
n_estimators = 2000
n_jobs = 1
tree_method = "gpu_hist"
colsample_bytree = 0.9092541904210051
gamma = 0.9382945636159261
lambda = 0.0
learning_rate = 0.04475073915281467
max_depth = 4
min_child_weight = 0.00012288624698766603
subsample = 0.6918425477748951

[xgboost_fit]
early_stopping_rounds = 50
verbose = true
