seed = 10
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 38
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    815,
]
dropout = 0.15625545235847013

[model.positional_encoding]
n = 84
sigma = 26.68890265209162
trainable = true
initialization = "normal"

[training]
batch_size = 128
lr = 0.004352130299295251
weight_decay = 5.512300311023067e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
