seed = 0
bins = "__none__"

[data]
path = "data/gesture"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 10
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 2
d_main = 468
dropout_first = 0.09939032917345078
dropout_second = 0.0
d_hidden = 593

[model.positional_encoding]
n = 85
sigma = 2.8313129850002237
trainable = true
initialization = "log-linear"

[training]
batch_size = 128
lr = 0.0002743639216734949
weight_decay = 2.4892624668374422e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
