seed = 4

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    310,
    1021,
]
dropout = 0.20263347821931366

[training]
batch_size = 512
lr = 8.114055216132572e-05
weight_decay = 0.0004955909084732345
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 250
value = "one"
subsample = "__none__"

[bins.tree]
min_samples_leaf = 105
min_impurity_decrease = 6.824803418087194e-09
