seed = 9
bins = "__none__"

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 84
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    112,
    349,
]
dropout = 0.0

[model.positional_encoding]
n = 32
sigma = 0.1645039036811343
trainable = true
initialization = "normal"

[training]
batch_size = 1024
lr = 0.00011508805774402678
weight_decay = 1.5183601229297129e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
