seed = 4

[data]
path = "data/california"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    533,
    352,
]
dropout = 0.0896808364503644

[training]
batch_size = 256
lr = 5.47189003274151e-05
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 91
subsample = "__none__"

[bins.tree]
min_samples_leaf = 51
min_impurity_decrease = 0.00043992776631368493
