seed = 0
bins = "__none__"

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    682,
]
dropout = 0.14985814975695538

[model.positional_encoding]
n = 21
sigma = 0.015145254135644213
trainable = true
initialization = "normal"

[training]
batch_size = 128
lr = 8.359415140030736e-05
weight_decay = 0.0009957621806163648
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
