seed = 4

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 125
num_embedding_arch = [
    "linear",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.resnet]
n_blocks = 5
d_main = 436
dropout_first = 0.4748403213362475
dropout_second = 0.21998376608029366
d_hidden = 749

[training]
batch_size = 1024
lr = 0.0003568091694761557
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
