seed = 8

[data]
path = "data/california"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    471,
]
dropout = 0.29568974694492123

[training]
batch_size = 256
lr = 5.854089154900891e-05
weight_decay = 0.00047793370519560145
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 225
value = "one"
subsample = "__none__"

[bins.tree]
min_samples_leaf = 31
min_impurity_decrease = 1.0209677260321267e-09
