seed = 3
bins = "__none__"

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = [
    "positional",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
autodis = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 4
d_main = 495
dropout_first = 0.40089687835936383
dropout_second = 0.4660971543261315
d_hidden = 1927

[model.positional_encoding]
n = 41
sigma = 0.0019211664512300698
trainable = false
initialization = "log-linear"

[training]
batch_size = 1024
lr = 0.0001015127095819321
weight_decay = 0.00021001770243147925
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
