seed = 6

[data]
path = "data/santander"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true

[model.mlp]
d_layers = [
    554,
    943,
    943,
    943,
    943,
    943,
    943,
    711,
]
dropout = 0.22998550041321342

[training]
batch_size = 1024
lr = 6.373938597551542e-05
weight_decay = 1.0365157516497304e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
