seed = 2
bins = "__none__"

[data]
path = "data/churn"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 61
num_embedding_arch = [
    "positional",
    "linear",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    806,
]
dropout = 0.0

[model.positional_encoding]
n = 119
sigma = 0.08344802592040095
trainable = true
initialization = "normal"

[training]
batch_size = 128
lr = 9.958325856110586e-05
weight_decay = 1.3479358747520765e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
