seed = 2
bins = "__none__"

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 63
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    919,
    332,
    332,
    332,
    332,
    332,
    584,
]
dropout = 0.1825971687832019

[model.positional_encoding]
n = 59
sigma = 0.12288877014509668
trainable = true
initialization = "normal"

[training]
batch_size = 512
lr = 0.00026672139741289777
weight_decay = 0.0004396287834292898
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
