seed = 1
bins = "__none__"

[data]
path = "data/eye"
T_cache = true

[data.T]
seed = 0
normalization = "standard"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 66
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 8
d_main = 214
dropout_first = 8.799337775383664e-05
dropout_second = 0.0
d_hidden = 314

[model.positional_encoding]
n = 67
sigma = 22.589215033701866
trainable = true
initialization = "log-linear"

[training]
batch_size = 128
lr = 0.0035831455038515337
weight_decay = 1.862536606795314e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
