seed = 3
bins = "__none__"

[data]
path = "data/house"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 30
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.mlp]
d_layers = [
    779,
    956,
    956,
    441,
]
dropout = 0.46181099062076963

[model.positional_encoding]
n = 44
sigma = 0.024351332121062545
trainable = true
initialization = "normal"

[training]
batch_size = 256
lr = 9.729726468488729e-05
weight_decay = 3.6804765746375783e-06
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
