seed = 9
bins = "__none__"

[data]
path = "data/adult"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 20
num_embedding_arch = [
    "positional",
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
mlp = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
fourier_features = "__none__"
memory_efficient = false

[model.resnet]
n_blocks = 7
d_main = 352
dropout_first = 0.3569581282193489
dropout_second = 0.06613109080075251
d_hidden = 811

[model.positional_encoding]
n = 115
sigma = 92.03044878063206
trainable = true
initialization = "log-linear"

[training]
batch_size = 256
lr = 0.00027706363553447783
weight_decay = 0.0
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
