seed = 12
bins = "__none__"

[data]
path = "data/higgs-small"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 5
num_embedding_arch = [
    "autodis",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
periodic_sigma = "__none__"
positional_encoding = "__none__"
fourier_features = "__none__"
memory_efficient = true

[model.mlp]
d_layers = [
    429,
    356,
    356,
    356,
    356,
    225,
]
dropout = 0.0

[model.autodis]
n_meta_embeddings = 69
temperature = 0.839498759335776

[training]
batch_size = 512
lr = 0.0001243201640379078
weight_decay = 6.53217867510626e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192
