seed = 11

[data]
path = "data/otto"
T_cache = true

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = 61
num_embedding_arch = [
    "linear",
    "relu",
]
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = false

[model.mlp]
d_layers = [
    663,
    518,
]
dropout = 0.452532109838354

[training]
batch_size = 512
lr = 0.00042364981560314064
weight_decay = 3.965896728549889e-05
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 147
tree = "__none__"
subsample = "__none__"
