seed = 2

[data]
path = "data/otto"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 4
bagging_temperature = 0.2764138416972912
depth = 9
l2_leaf_reg = 2.7913967458734286
leaf_estimation_iterations = 2
learning_rate = 0.06606187698158077

[catboost_fit]
logging_level = "Verbose"
