seed = 6

[data]
path = "data/microsoft"
T_cache = true

[data.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[model]
d_num_embedding = "__none__"
num_embedding_arch = []
d_cat_embedding = "__none__"
resnet = "__none__"
transformer = "__none__"
transformer_default = false
transformer_baseline = true
memory_efficient = true

[model.mlp]
d_layers = [
    796,
    763,
    763,
    763,
    864,
]
dropout = 0.336485857185205

[training]
batch_size = 1024
lr = 9.153601412760631e-05
weight_decay = 0.0009810183471746492
optimizer = "AdamW"
patience = 16
n_epochs = inf
eval_batch_size = 8192

[bins]
count = 11
value = "one"
subsample = "__none__"

[bins.tree]
min_samples_leaf = 101
min_impurity_decrease = 5.8521634404660975e-09
